# Generated by Django 3.0.7 on 2020-08-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200709_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مثاله ویژه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('P', 'منتشر\u200cشده'), ('D', 'پیش\u200cنویس'), ('I', 'در\u200cحال بررسی'), ('B', 'رد\u200cشده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
